<head>
    <title>How Late is my Doctor?</title>
    <meta charset="utf-8" />
    <meta name="google-site-verification" content="84C-kFLmCZgIPgtYPCa-wbW5Mcb2XIZaqlvtK6fkBq0" />
    <meta name="twitter:card" content="photo">
    <meta name="twitter:image" content="/master/images/twitter-image.jpg">
    <meta name="twitter:title" content="How-Late Software">
    <meta name="twitter:domain" content="how-late.com">
    <meta name="twitter:site" content="@HowLateIsMyAppt">
    <meta name="twitter:creator" content="@HowLateIsMyAppt">
    <meta name="twitter:image:width" content="475">
    <meta name="twitter:image:height" content="323">
    <meta name="fb:admins" content="HowLateIsMyAppointment">
    <meta name="fb:app_id" content="466443880106725">
    <meta property="og:title" content="How-Late Software">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://how-late.com/master/images/logos/logo_lg_sq_trans.png" itemprop="how late logo">
    <meta property="og:url" content="https://www.how-late.com">
    <meta property="og:description" content="This is cool.  Share it with your friends.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="How-Late Software allows doctors to tell their patients if their appointment is running late.  Allows patients to see if their doctors appointment is running late.">
    <meta name="keywords" content="EHR,EMR,EMIS,BestPractice,Medical Director, MedTech, ZedMed,Genie,AllScripts,Cerner,AthenaHealth,Neomed,Practice Fusion,Healthware,Alerce,EpicCare,NextGen Ambulatory,Greenway Primesuite,CPSI,PlatinumEMR,Athena Clinicals, eClinical Works, Metacare, Caregiver Desktop, Raintree, eHealth Files, Keychart EHR, Centrihealth, eMedRec, Phymedica,Agility EHR,OfficeEMR, doctor running late app, how late is my appointment, doctor,medical practitioners,clinic,surgery,patient,appointment">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />

    <!-- Generated by realfavicongenerator.net -->

    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">      


    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap-responsive.min.css" rel="stylesheet">

    <link href="howlate-brochure.css" rel="stylesheet">

    <style>
        body { padding-top: 70px; }
    </style>
</head>