<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-08 at 15:53:53.
 */
class AgentApiTest extends PHPUnit_Framework_TestCase {

    /**
     * @var AgentApi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $Organisation = Organisation::getInstance('CCEOW', 'OrgID');
        $Clinic = Clinic::getInstance($Organisation->OrgID, 139);

        $this->object = new AgentApi($Organisation, $Clinic);
        
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }


    public function testappt11() {
        $time_now = 76100;
        $appt_list = array(
            array ('Provider' => 'Dr Joseph Lister','ApptStatus' => 'Booked','ApptType' => '','ArrivalTime' => '45805','AppointmentTime' => '66900',
                'ConsultationTime' => '76025','Duration' => '900','MobilePhone' => '49666765765','ConsentSMS' => '1')
            );

        $_POST['appt'] = $appt_list;
        $_POST = array('credentials' => 'demo,e8dc4081b13434b45189a720b77b6818', 'time_now' => $time_now, 'appt' => $appt_list);

        //ob_start();
        $this->object->appt();

        //$ret = ob_get_clean();
        
        //$ret = json_decode($ret,true);
        
        //$this->assertEquals($ret['code'], 200);  // ensures one row was updated

        //$appts = $ret['response']['Appointments'];
        
        //var_dump($appts);
        
//        $specific = array_filter($appts, 
//            function($item) { 
//            return ($item['AppointmentTime'] == '66900');});
//        $first_row = array_values($specific)[0];
//            $this->assertEquals($first_row['SecondsLate'],9125);
    }
    

}
