<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$a = 
array (
  'Summary' => 
  array (
    0 => 
    array (
      'Practitioner' => 'Dr McPhee (Ruby St)',
      'Actual Late' => 8342,
    ),
    1 => 
    array (
      'Practitioner' => 'Dr Gramae Pagel',
      'Actual Late' => 9842,
    ),
    2 => 
    array (
      'Practitioner' => 'Dr Hillary Vincent',
      'Actual Late' => 8342,
    ),
    3 => 
    array (
      'Practitioner' => 'Dr Ikenna Ilechukwu',
      'Actual Late' => 9842,
    ),
    4 => 
    array (
      'Practitioner' => 'Dr Jess Gaughan',
      'Actual Late' => 8342,
    ),
    5 => 
    array (
      'Practitioner' => 'Dr Joy Enwere',
      'Actual Late' => 8925,
    ),
    6 => 
    array (
      'Practitioner' => 'Dr Mitch Christensen',
      'Actual Late' => 8342,
    ),
    7 => 
    array (
      'Practitioner' => 'Dr Thushanthi Wijeratne ',
      'Actual Late' => 0,
    ),
    8 => 
    array (
      'Practitioner' => 'Dr Tore Nordland',
      'Actual Late' => 8932,
    ),
    9 => 
    array (
      'Practitioner' => 'Mayfair Ridge Staff',
      'Actual Late' => 0,
    ),
    10 => 
    array (
      'Practitioner' => 'Mr  Telehealth',
      'Actual Late' => 0,
    ),
    11 => 
    array (
      'Practitioner' => 'Mrs Christine Crook',
      'Actual Late' => 11221,
    ),
    12 => 
    array (
      'Practitioner' => 'Ms Janette Dillon',
      'Actual Late' => 5942,
    ),
    13 => 
    array (
      'Practitioner' => 'Registered Nurse',
      'Actual Late' => 11566,
    ),
    14 => 
    array (
      'Practitioner' => 'Z Staff',
      'Actual Late' => 10791,
    ),
  ),
  'Notified' => 
  array (
    0 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36825,
      'Duration' => '600',
      'MobilePhone' => '0488 25 11 08',
      'ConsentSMS' => '1',
      'LatePredicted' => 2625,
    ),
    1 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38025,
      'Duration' => '600',
      'MobilePhone' => '0459 794 018',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    2 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38625,
      'Duration' => '600',
      'MobilePhone' => '0409277368',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    3 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36242,
      'Duration' => '1200',
      'MobilePhone' => '0419026232',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    4 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37442,
      'Duration' => '1200',
      'MobilePhone' => '0421989444',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    5 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36832,
      'Duration' => '600',
      'MobilePhone' => '0428 418 764',
      'ConsentSMS' => '1',
      'LatePredicted' => 3832,
    ),
    6 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38032,
      'Duration' => '600',
      'MobilePhone' => '0459227595',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    7 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38632,
      'Duration' => '600',
      'MobilePhone' => '0428680038',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    8 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39232,
      'Duration' => '600',
      'MobilePhone' => '0409 907 557',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    9 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39832,
      'Duration' => '600',
      'MobilePhone' => '0439533323',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    10 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40432,
      'Duration' => '600',
      'MobilePhone' => '0437016671',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    11 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42832,
      'Duration' => '600',
      'MobilePhone' => '0438 871 896',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
  ),
  'Final' => 
  array (
    0 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36842,
      'Duration' => '600',
      'MobilePhone' => '0457 079 351',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    1 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37442,
      'Duration' => '600',
      'MobilePhone' => '0416422270',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    2 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38042,
      'Duration' => '600',
      'MobilePhone' => '0400539370',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    3 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38642,
      'Duration' => '600',
      'MobilePhone' => '0431343866',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    4 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36825,
      'Duration' => '600',
      'MobilePhone' => '0488 25 11 08',
      'ConsentSMS' => '1',
      'LatePredicted' => 2625,
    ),
    5 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38025,
      'Duration' => '600',
      'MobilePhone' => '0459 794 018',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    6 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38625,
      'Duration' => '600',
      'MobilePhone' => '0409277368',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    7 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36242,
      'Duration' => '1200',
      'MobilePhone' => '0419026232',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    8 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37442,
      'Duration' => '1200',
      'MobilePhone' => '0421989444',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    9 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36832,
      'Duration' => '600',
      'MobilePhone' => '0428 418 764',
      'ConsentSMS' => '1',
      'LatePredicted' => 3832,
    ),
    10 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38032,
      'Duration' => '600',
      'MobilePhone' => '0459227595',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    11 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38632,
      'Duration' => '600',
      'MobilePhone' => '0428680038',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    12 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39232,
      'Duration' => '600',
      'MobilePhone' => '0409 907 557',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    13 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39832,
      'Duration' => '600',
      'MobilePhone' => '0439533323',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    14 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40432,
      'Duration' => '600',
      'MobilePhone' => '0437016671',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    15 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42832,
      'Duration' => '600',
      'MobilePhone' => '0438 871 896',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    16 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Completed',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '34246',
      'AppointmentTime' => '34800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39466,
      'Duration' => '600',
      'MobilePhone' => '0419712811',
      'ConsentSMS' => '1',
      'LatePredicted' => 4666,
    ),
    17 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '25500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36291,
      'Duration' => '300',
      'MobilePhone' => '0435110255',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    18 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36891,
      'Duration' => '300',
      'MobilePhone' => '0419 322 056',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    19 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37191,
      'Duration' => '300',
      'MobilePhone' => '0407572282',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    20 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37491,
      'Duration' => '300',
      'MobilePhone' => '0417967979',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    21 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37791,
      'Duration' => '300',
      'MobilePhone' => '0469379644',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    22 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27300',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38091,
      'Duration' => '300',
      'MobilePhone' => '0427 004 690',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    23 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38391,
      'Duration' => '300',
      'MobilePhone' => '0413 884 490',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    24 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27900',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38691,
      'Duration' => '300',
      'MobilePhone' => '0400754455',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    25 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38991,
      'Duration' => '300',
      'MobilePhone' => '0458695694',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    26 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39291,
      'Duration' => '300',
      'MobilePhone' => '0400449364',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    27 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39591,
      'Duration' => '300',
      'MobilePhone' => '0421419145',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    28 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39891,
      'Duration' => '300',
      'MobilePhone' => '0488796838',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    29 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40191,
      'Duration' => '300',
      'MobilePhone' => '0407 971 929',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    30 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40491,
      'Duration' => '300',
      'MobilePhone' => '0459381130',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    31 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40791,
      'Duration' => '1800',
      'MobilePhone' => '04000 644 85',
      'ConsentSMS' => '1',
      'LatePredicted' => 4791,
    ),
  ),
  'All Candidates' => 
  array (
    0 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '30439',
      'AppointmentTime' => '30600',
      'ConsultationTime' => '30817',
      'ConsultPredicted' => '30817',
      'Duration' => '600',
      'MobilePhone' => '0429 855 106',
      'ConsentSMS' => '1',
      'LatePredicted' => 217,
    ),
    1 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '30142',
      'AppointmentTime' => '31200',
      'ConsultationTime' => '31696',
      'ConsultPredicted' => '31696',
      'Duration' => '600',
      'MobilePhone' => '0427660145',
      'ConsentSMS' => '1',
      'LatePredicted' => 496,
    ),
    2 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Completed',
      'ApptType' => 'Teleconference',
      'ArrivalTime' => '29958',
      'AppointmentTime' => '30600',
      'ConsultationTime' => '31708',
      'ConsultPredicted' => '31708',
      'Duration' => '1800',
      'MobilePhone' => 'no mobile',
      'ConsentSMS' => '0',
      'LatePredicted' => 1108,
    ),
    3 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Recall',
      'ArrivalTime' => '32081',
      'AppointmentTime' => '32400',
      'ConsultationTime' => '32641',
      'ConsultPredicted' => '32641',
      'Duration' => '600',
      'MobilePhone' => '0458539136',
      'ConsentSMS' => '1',
      'LatePredicted' => 241,
    ),
    4 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '32590',
      'AppointmentTime' => '32400',
      'ConsultationTime' => '32642',
      'ConsultPredicted' => '32642',
      'Duration' => '1800',
      'MobilePhone' => '0400024500',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    5 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '31988',
      'AppointmentTime' => '32400',
      'ConsultationTime' => '32773',
      'ConsultPredicted' => '32773',
      'Duration' => '600',
      'MobilePhone' => '0488 985 631',
      'ConsentSMS' => '1',
      'LatePredicted' => 373,
    ),
    6 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Completed',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '33297',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '33881',
      'ConsultPredicted' => '33881',
      'Duration' => '600',
      'MobilePhone' => '0455 536 994',
      'ConsentSMS' => '1',
      'LatePredicted' => 881,
    ),
    7 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '32533',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '34038',
      'ConsultPredicted' => '34038',
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '0',
      'LatePredicted' => 1038,
    ),
    8 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '34398',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '34808',
      'ConsultPredicted' => '34808',
      'Duration' => '1800',
      'MobilePhone' => '0438645624',
      'ConsentSMS' => '1',
      'LatePredicted' => 608,
    ),
    9 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '31669',
      'AppointmentTime' => '32400',
      'ConsultationTime' => '35178',
      'ConsultPredicted' => '35178',
      'Duration' => '600',
      'MobilePhone' => '0427874450',
      'ConsentSMS' => '1',
      'LatePredicted' => 2778,
    ),
    10 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'At billing',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '33784',
      'AppointmentTime' => '33600',
      'ConsultationTime' => '35297',
      'ConsultPredicted' => '35297',
      'Duration' => '600',
      'MobilePhone' => '0457257121',
      'ConsentSMS' => '1',
      'LatePredicted' => 1697,
    ),
    11 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Completed',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '35384',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '35390',
      'ConsultPredicted' => '35390',
      'Duration' => '600',
      'MobilePhone' => '0455 536 994',
      'ConsentSMS' => '1',
      'LatePredicted' => 2390,
    ),
    12 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Completed',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '34244',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '35391',
      'ConsultPredicted' => '35391',
      'Duration' => '600',
      'MobilePhone' => '0487100076',
      'ConsentSMS' => '1',
      'LatePredicted' => 1191,
    ),
    13 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'With doctor',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '35474',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '35521',
      'ConsultPredicted' => '35521',
      'Duration' => '1800',
      'MobilePhone' => '0400662068',
      'ConsentSMS' => '1',
      'LatePredicted' => -479,
    ),
    14 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'With doctor',
      'ApptType' => 'Coal Board Medical',
      'ArrivalTime' => '33824',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '35566',
      'ConsultPredicted' => '35566',
      'Duration' => '3600',
      'MobilePhone' => '0428688771',
      'ConsentSMS' => '1',
      'LatePredicted' => -434,
    ),
    15 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'At billing',
      'ApptType' => 'Recall',
      'ArrivalTime' => '34455',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '35677',
      'ConsultPredicted' => '35677',
      'Duration' => '600',
      'MobilePhone' => '0408 68 36 02',
      'ConsentSMS' => '1',
      'LatePredicted' => 1477,
    ),
    16 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'With doctor',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '35901',
      'AppointmentTime' => '34800',
      'ConsultationTime' => '35925',
      'ConsultPredicted' => '35925',
      'Duration' => '600',
      'MobilePhone' => '0455 536 994',
      'ConsentSMS' => '1',
      'LatePredicted' => 1125,
    ),
    17 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'With doctor',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '34522',
      'AppointmentTime' => '34800',
      'ConsultationTime' => '35932',
      'ConsultPredicted' => '35932',
      'Duration' => '600',
      'MobilePhone' => '0408683602',
      'ConsentSMS' => '1',
      'LatePredicted' => 1132,
    ),
    18 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8342,
    ),
    19 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 9842,
    ),
    20 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8342,
    ),
    21 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 9842,
    ),
    22 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8342,
    ),
    23 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8342,
    ),
    24 => 
    array (
      'Provider' => 'Ms Janette Dillon',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '30000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '35942',
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 5942,
    ),
    25 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '25200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 35991,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 10791,
    ),
    26 => 
    array (
      'Provider' => 'Dr Thushanthi Wijeratne (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '36000',
      'Duration' => '12000',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    27 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Waiting',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '35525',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36242,
      'Duration' => '600',
      'MobilePhone' => '0418768465',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    28 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36242,
      'Duration' => '1200',
      'MobilePhone' => '0419026232',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    29 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '25500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36291,
      'Duration' => '300',
      'MobilePhone' => '0435110255',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    30 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36525,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8925,
    ),
    31 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36532,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 8932,
    ),
    32 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '25800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36591,
      'Duration' => '300',
      'MobilePhone' => '0417785768',
      'ConsentSMS' => '0',
      'LatePredicted' => 10791,
    ),
    33 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '34200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36825,
      'Duration' => '600',
      'MobilePhone' => '0488 25 11 08',
      'ConsentSMS' => '1',
      'LatePredicted' => 2625,
    ),
    34 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '33000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36832,
      'Duration' => '600',
      'MobilePhone' => '0428 418 764',
      'ConsentSMS' => '1',
      'LatePredicted' => 3832,
    ),
    35 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36842,
      'Duration' => '600',
      'MobilePhone' => '0457 079 351',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    36 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 36891,
      'Duration' => '300',
      'MobilePhone' => '0419 322 056',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    37 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37191,
      'Duration' => '300',
      'MobilePhone' => '0407572282',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    38 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37321,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 11221,
    ),
    39 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37425,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '0',
      'LatePredicted' => 825,
    ),
    40 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Waiting',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '35408',
      'AppointmentTime' => '35400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37432,
      'Duration' => '600',
      'MobilePhone' => '0447 340 882',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    41 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37442,
      'Duration' => '600',
      'MobilePhone' => '0416422270',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    42 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37442,
      'Duration' => '1200',
      'MobilePhone' => '0421989444',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    43 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '26700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37491,
      'Duration' => '300',
      'MobilePhone' => '0417967979',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    44 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 37791,
      'Duration' => '300',
      'MobilePhone' => '0469379644',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    45 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '37800',
      'Duration' => '1200',
      'MobilePhone' => '0429688361',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    46 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '37800',
      'Duration' => '1800',
      'MobilePhone' => '0406 54 90 66',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    47 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38025,
      'Duration' => '600',
      'MobilePhone' => '0459 794 018',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    48 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38032,
      'Duration' => '600',
      'MobilePhone' => '0459227595',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    49 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38042,
      'Duration' => '600',
      'MobilePhone' => '0400539370',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    50 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27300',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38091,
      'Duration' => '300',
      'MobilePhone' => '0427 004 690',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    51 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38391,
      'Duration' => '300',
      'MobilePhone' => '0413 884 490',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    52 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38625,
      'Duration' => '600',
      'MobilePhone' => '0409277368',
      'ConsentSMS' => '1',
      'LatePredicted' => 825,
    ),
    53 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38632,
      'Duration' => '600',
      'MobilePhone' => '0428680038',
      'ConsentSMS' => '1',
      'LatePredicted' => 2032,
    ),
    54 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38642,
      'Duration' => '600',
      'MobilePhone' => '0431343866',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    55 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Waiting',
      'ApptType' => 'Recall',
      'ArrivalTime' => '34868',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38642,
      'Duration' => '1200',
      'MobilePhone' => '0404065907',
      'ConsentSMS' => '1',
      'LatePredicted' => 242,
    ),
    56 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27900',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38691,
      'Duration' => '300',
      'MobilePhone' => '0400754455',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    57 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 38991,
      'Duration' => '300',
      'MobilePhone' => '0458695694',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    58 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39000,
      'Duration' => '1200',
      'MobilePhone' => '0402 335 006',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    59 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '27600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39166,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 11566,
    ),
    60 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '37800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39232,
      'Duration' => '600',
      'MobilePhone' => '0409 907 557',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    61 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39291,
      'Duration' => '300',
      'MobilePhone' => '0400449364',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    62 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Completed',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '34246',
      'AppointmentTime' => '34800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39466,
      'Duration' => '600',
      'MobilePhone' => '0419712811',
      'ConsentSMS' => '1',
      'LatePredicted' => 4666,
    ),
    63 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '28800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39591,
      'Duration' => '300',
      'MobilePhone' => '0421419145',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    64 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Meeting',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '39600',
      'Duration' => '1200',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    65 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '39600',
      'Duration' => '1200',
      'MobilePhone' => '0457648871',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    66 => 
    array (
      'Provider' => 'Mr  Telehealth',
      'Status' => 'Booked',
      'ApptType' => 'Teleconference',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '39600',
      'Duration' => '3600',
      'MobilePhone' => '0427350651',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    67 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39600,
      'Duration' => '1800',
      'MobilePhone' => '0488132795',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    68 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '38400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39832,
      'Duration' => '600',
      'MobilePhone' => '0439533323',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    69 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 39891,
      'Duration' => '300',
      'MobilePhone' => '0488796838',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    70 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40191,
      'Duration' => '300',
      'MobilePhone' => '0407 971 929',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    71 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '40200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '40200',
      'Duration' => '600',
      'MobilePhone' => '0448110005',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    72 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '40200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '40200',
      'Duration' => '600',
      'MobilePhone' => '0439 106 901',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    73 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '39000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40432,
      'Duration' => '600',
      'MobilePhone' => '0437016671',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    74 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '29700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40491,
      'Duration' => '300',
      'MobilePhone' => '0459381130',
      'ConsentSMS' => '1',
      'LatePredicted' => 10791,
    ),
    75 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '36000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40791,
      'Duration' => '1800',
      'MobilePhone' => '04000 644 85',
      'ConsentSMS' => '1',
      'LatePredicted' => 4791,
    ),
    76 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '40800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40800,
      'Duration' => '600',
      'MobilePhone' => '0429 876 868',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    77 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '40800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 40800,
      'Duration' => '600',
      'MobilePhone' => '0429877807',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    78 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '40800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '40800',
      'Duration' => '1200',
      'MobilePhone' => '0400479477',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    79 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Waiting',
      'ApptType' => 'Coal Board Medical',
      'ArrivalTime' => '33822',
      'AppointmentTime' => '39600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 41032,
      'Duration' => '1800',
      'MobilePhone' => '0428688771',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    80 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 41400,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    81 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 41400,
      'Duration' => '600',
      'MobilePhone' => '0407735011',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    82 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 41400,
      'Duration' => '1800',
      'MobilePhone' => '0473 195 157',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    83 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '41400',
      'Duration' => '1200',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    84 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42000,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    85 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42000,
      'Duration' => '600',
      'MobilePhone' => '0407735011',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    86 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42000,
      'Duration' => '1200',
      'MobilePhone' => '0458 738 550',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    87 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '42600',
      'Duration' => '1200',
      'MobilePhone' => '0437985870',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    88 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '41400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 42832,
      'Duration' => '600',
      'MobilePhone' => '0438 871 896',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    89 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '43200',
      'Duration' => '600',
      'MobilePhone' => '0459316967',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    90 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '43200',
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    91 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43200,
      'Duration' => '2400',
      'MobilePhone' => '0448 821 778',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    92 => 
    array (
      'Provider' => 'Mr  Telehealth',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43200,
      'Duration' => '2400',
      'MobilePhone' => '0448 821 778',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    93 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43200,
      'Duration' => '1800',
      'MobilePhone' => '0405098780',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    94 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43432,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 1432,
    ),
    95 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43800,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    96 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 43800,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    97 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '43800',
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    98 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '42600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 44032,
      'Duration' => '600',
      'MobilePhone' => '0429 874 206',
      'ConsentSMS' => '1',
      'LatePredicted' => 1432,
    ),
    99 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '44400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 44400,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    100 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '44400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 44400,
      'Duration' => '600',
      'MobilePhone' => '0410405152',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    101 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Coal Board Medical',
      'ArrivalTime' => '0',
      'AppointmentTime' => '44400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 44400,
      'Duration' => '3600',
      'MobilePhone' => '0407 382 353',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    102 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '43200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 44632,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 1432,
    ),
    103 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Meeting',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '45000',
      'Duration' => '3600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    104 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45000,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    105 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45000,
      'Duration' => '600',
      'MobilePhone' => '0428822267',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    106 => 
    array (
      'Provider' => 'Mrs Christine Crook',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45000,
      'Duration' => '1800',
      'MobilePhone' => '0427783248',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    107 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45600,
      'Duration' => '600',
      'MobilePhone' => '0456 621 173',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    108 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45600,
      'Duration' => '600',
      'MobilePhone' => '0497 053 846',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    109 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '45600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 45600,
      'Duration' => '1200',
      'MobilePhone' => '0438877156',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    110 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '46800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '46800',
      'Duration' => '600',
      'MobilePhone' => '0439 755 103',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    111 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '46800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '46800',
      'Duration' => '600',
      'MobilePhone' => '0439 210 108',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    112 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '46800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 46800,
      'Duration' => '1200',
      'MobilePhone' => '0428853435',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    113 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '47400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 47400,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    114 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '47400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 47400,
      'Duration' => '600',
      'MobilePhone' => '0418728969',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    115 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Home visit',
      'ArrivalTime' => '0',
      'AppointmentTime' => '47700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '47700',
      'Duration' => '900',
      'MobilePhone' => '0488922982',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    116 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 48000,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    117 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '48600',
      'Duration' => '600',
      'MobilePhone' => '0402 940 571',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    118 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Coal Board Medical',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '48600',
      'Duration' => '2400',
      'MobilePhone' => '0407 382 353',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    119 => 
    array (
      'Provider' => 'Dr Joy Enwere (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 48600,
      'Duration' => '600',
      'MobilePhone' => '0459222325',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    120 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Venesection',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 48600,
      'Duration' => '1200',
      'MobilePhone' => '0401 872 919',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    121 => 
    array (
      'Provider' => 'Mr  Telehealth',
      'Status' => 'Booked',
      'ApptType' => 'Teleconference',
      'ArrivalTime' => '0',
      'AppointmentTime' => '48600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '48600',
      'Duration' => '1800',
      'MobilePhone' => '0418136587',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    122 => 
    array (
      'Provider' => 'Dr Mitchell Christensen (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '49200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '49200',
      'Duration' => '1200',
      'MobilePhone' => '0488273216',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    123 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '49800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 49800,
      'Duration' => '600',
      'MobilePhone' => '0402101756',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    124 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '49800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '49800',
      'Duration' => '600',
      'MobilePhone' => '0438 170940',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    125 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '50400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '50400',
      'Duration' => '1800',
      'MobilePhone' => '0404581988',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    126 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '50400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 50400,
      'Duration' => '600',
      'MobilePhone' => '0408910455',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    127 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '51000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '51000',
      'Duration' => '2100',
      'MobilePhone' => '0412905696',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    128 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '51000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 51000,
      'Duration' => '2400',
      'MobilePhone' => '0412905696',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    129 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '51000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 51000,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    130 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '51300',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '51300',
      'Duration' => '900',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    131 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '52200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 52200,
      'Duration' => '900',
      'MobilePhone' => '0418 876 439',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    132 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '52200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 52200,
      'Duration' => '900',
      'MobilePhone' => '0427822939',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    133 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '52200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '52200',
      'Duration' => '1200',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    134 => 
    array (
      'Provider' => 'Mr  Telehealth',
      'Status' => 'Booked',
      'ApptType' => 'Teleconference',
      'ArrivalTime' => '0',
      'AppointmentTime' => '52200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '52200',
      'Duration' => '3600',
      'MobilePhone' => '0448255437',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    135 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '53100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 53100,
      'Duration' => '900',
      'MobilePhone' => '0427726428',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    136 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '53100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 53100,
      'Duration' => '900',
      'MobilePhone' => '0423962190',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    137 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '53100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 53100,
      'Duration' => '900',
      'MobilePhone' => '0400243107',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    138 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '53400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 53400,
      'Duration' => '1200',
      'MobilePhone' => '0400 292 293',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    139 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '53400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 53400,
      'Duration' => '600',
      'MobilePhone' => '0488 998 097',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    140 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54000,
      'Duration' => '1200',
      'MobilePhone' => '0407113768',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    141 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54000,
      'Duration' => '900',
      'MobilePhone' => 'no mobile',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    142 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54000,
      'Duration' => '900',
      'MobilePhone' => '0437 095 759',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    143 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54000,
      'Duration' => '600',
      'MobilePhone' => '0426881988',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    144 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54600,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    145 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '54600',
      'Duration' => '600',
      'MobilePhone' => '0407761337',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    146 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '54900',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 54900,
      'Duration' => '900',
      'MobilePhone' => '0400164410',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    147 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 55200,
      'Duration' => '2400',
      'MobilePhone' => '0439024442',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    148 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 55200,
      'Duration' => '600',
      'MobilePhone' => '0425283011',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    149 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '55800',
      'Duration' => '1800',
      'MobilePhone' => '0418155642',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    150 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '55800',
      'Duration' => '600',
      'MobilePhone' => '0413 484 465',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    151 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '55800',
      'Duration' => '1200',
      'MobilePhone' => '0414720219',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    152 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '55800',
      'Duration' => '600',
      'MobilePhone' => '0403788463',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    153 => 
    array (
      'Provider' => 'Mayfair Ridge Staff',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '55800',
      'Duration' => '900',
      'MobilePhone' => '0437441998',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    154 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '55800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 55800,
      'Duration' => '600',
      'MobilePhone' => '0439079686',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    155 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '56400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 56400,
      'Duration' => '600',
      'MobilePhone' => '0467444690',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    156 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '56400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 56400,
      'Duration' => '600',
      'MobilePhone' => '0437 008 464',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    157 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '56400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 56400,
      'Duration' => '1200',
      'MobilePhone' => '0487240982',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    158 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Long appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '56700',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '56700',
      'Duration' => '900',
      'MobilePhone' => '0404484180',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    159 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Recall',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 57000,
      'Duration' => '1200',
      'MobilePhone' => '0400213106',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    160 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 57600,
      'Duration' => '2400',
      'MobilePhone' => '0408 834 277',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    161 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 57600,
      'Duration' => '900',
      'MobilePhone' => '0438266700',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    162 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '57600',
      'Duration' => '600',
      'MobilePhone' => '0487 265 767',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    163 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '57600',
      'Duration' => '600',
      'MobilePhone' => '0427225846',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    164 => 
    array (
      'Provider' => 'Registered Nurse',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '57600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 57600,
      'Duration' => '600',
      'MobilePhone' => '0429631842',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    165 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '58200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 58200,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    166 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '58200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 58200,
      'Duration' => '1200',
      'MobilePhone' => '0487240982',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    167 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '58500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 58500,
      'Duration' => '900',
      'MobilePhone' => '0407821592',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    168 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '58500',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '58500',
      'Duration' => '900',
      'MobilePhone' => '0401348512',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    169 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '58800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 58800,
      'Duration' => '600',
      'MobilePhone' => '0428 885 063',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    170 => 
    array (
      'Provider' => 'Dr Gramae Pagel (Mayfair Ridge)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '59400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 59400,
      'Duration' => '900',
      'MobilePhone' => '0418746939',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    171 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '59400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 59400,
      'Duration' => '900',
      'MobilePhone' => '0427561432',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    172 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '59400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 59400,
      'Duration' => '600',
      'MobilePhone' => '0448024299',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    173 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '59400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 59400,
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    174 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '59400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '59400',
      'Duration' => '600',
      'MobilePhone' => '0429 874 803',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    175 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '60000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 60000,
      'Duration' => '1200',
      'MobilePhone' => '0418876441',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    176 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '60000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 60000,
      'Duration' => '600',
      'MobilePhone' => '0408718782',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    177 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '60300',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 60300,
      'Duration' => '900',
      'MobilePhone' => '',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    178 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '60600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '60600',
      'Duration' => '1200',
      'MobilePhone' => '0405 222 887',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    179 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '60600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 60600,
      'Duration' => '600',
      'MobilePhone' => '0427783248',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    180 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 61200,
      'Duration' => '1200',
      'MobilePhone' => '0427090686',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    181 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 61200,
      'Duration' => '900',
      'MobilePhone' => '0427378036',
      'ConsentSMS' => '0',
      'LatePredicted' => 0,
    ),
    182 => 
    array (
      'Provider' => 'Dr Ikenna (Ike) Ilechukwu (Mayfair)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '61200',
      'Duration' => '3000',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    183 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 61200,
      'Duration' => '600',
      'MobilePhone' => '0438185627',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    184 => 
    array (
      'Provider' => 'Dr Jessica Gaughan',
      'Status' => 'Booked',
      'ApptType' => 'Immunisation',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 61800,
      'Duration' => '1200',
      'MobilePhone' => '0408988940',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    185 => 
    array (
      'Provider' => 'Dr Tore Nordland (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '61800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 61800,
      'Duration' => '600',
      'MobilePhone' => '0418271655',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    186 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '62400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 62400,
      'Duration' => '1200',
      'MobilePhone' => '0427168163',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    187 => 
    array (
      'Provider' => 'Dr Hillary Vincent (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '63000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '63000',
      'Duration' => '900',
      'MobilePhone' => '0411546703',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    188 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Excision',
      'ArrivalTime' => '0',
      'AppointmentTime' => '63600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 63600,
      'Duration' => '1200',
      'MobilePhone' => '0428824703',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    189 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '64800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '64800',
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    190 => 
    array (
      'Provider' => 'Z Staff',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '65100',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 65100,
      'Duration' => '300',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    191 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '65400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '65400',
      'Duration' => '600',
      'MobilePhone' => '0409057890',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    192 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '66000',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 66000,
      'Duration' => '600',
      'MobilePhone' => '0447 467 630',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    193 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '66600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 66600,
      'Duration' => '600',
      'MobilePhone' => '0407851229',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    194 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '67200',
      'ConsultationTime' => '0',
      'ConsultPredicted' => 67200,
      'Duration' => '600',
      'MobilePhone' => '0424637353',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    195 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Other',
      'ArrivalTime' => '0',
      'AppointmentTime' => '68400',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '68400',
      'Duration' => '600',
      'MobilePhone' => '',
      'ConsentSMS' => '',
      'LatePredicted' => 0,
    ),
    196 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '69600',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '69600',
      'Duration' => '600',
      'MobilePhone' => '0427 227 667',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
    197 => 
    array (
      'Provider' => 'Dr Ewen McPhee (Ruby St)',
      'Status' => 'Booked',
      'ApptType' => 'Standard appt.',
      'ArrivalTime' => '0',
      'AppointmentTime' => '70800',
      'ConsultationTime' => '0',
      'ConsultPredicted' => '70800',
      'Duration' => '600',
      'MobilePhone' => '0457442868',
      'ConsentSMS' => '1',
      'LatePredicted' => 0,
    ),
  ),
);

        



?>