<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:50.
 */
class agentTest extends PHPUnit_Framework_TestCase {

    /**
     * @var agent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new agent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers agent::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $i = agent::getInstance('CCEOW',139);
        $this->assertEquals($i->ClinicName, 'Demo Clinic Haymarket');
        
    }

    /**
     * @covers agent::get_exe
     * @todo   Implement testGet_exe().
     */
    public function testGet_exe() {
        // Remove the following lines when you implement this test.
        $i = agent::getInstance('CCEOW',139);
        //$i->get_exe();
        $this->assertNotEmpty($i);
        
    }

    /**
     * @covers agent::valid_versions
     * @todo   Implement testValid_versions().
     */
    public function testValid_versions() {
        // Remove the following lines when you implement this test.
        $i = agent::getInstance('CCEOW',139);
        $this->assertEquals($i->Platform, 'x64');
        $v = $i->valid_versions();
        $this->assertContains('3.2.1.2', $v);
        $this->assertContains('2.5.6.5', $v);
    }
}
