<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-15 at 05:48:20.
 */
class ApiTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Api
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Api('CCEOW',139);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    
    public function testConstructor() {
        $this->object = new Api('CCEOW', 139);
        
        $this->assertNotEmpty($this->object);
        $this->assertEquals($this->object->OrgID,'CCEOW');
        
        
    }
    
    /**
     * @covers Api::updateLateness
     * @todo   Implement testUpdateLateness().
     */
    public function testUpdateLateness() {
        // Remove the following lines when you implement this test.
        $PractitionerName = "Dr Joseph Lister";
        $NewLate = 55;
        $this->object->updateLateness($NewLate, $PractitionerName);
        
        
        
    }

    /**
     * @covers Api::updateSessions
     * @todo   Implement testUpdateSessions().
     */
    public function testUpdateSessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::updateApptTypes
     * @todo   Implement testUpdateApptTypes().
     */
    public function testUpdateApptTypes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::updateApptStatus
     * @todo   Implement testUpdateApptStatus().
     */
    public function testUpdateApptStatus() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::areCredentialsValid
     * @todo   Implement testAreCredentialsValid().
     */
    public function testAreCredentialsValid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::notify
     * @todo   Implement testNotify().
     */
    public function testNotify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::agent_version_target
     * @todo   Implement testAgent_version_target().
     */
    public function testAgent_version_target() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::agent_version
     * @todo   Implement testAgent_version().
     */
    public function testAgent_version() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::get_exe
     * @todo   Implement testGet_exe().
     */
    public function testGet_exe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::notifybulk
     * @todo   Implement testNotifybulk().
     */
    public function testNotifybulk() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::processAppointments
     * @todo   Implement testProcessAppointments().
     */
    public function testProcessAppointments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Api::providerList
     * @todo   Implement testProviderList().
     */
    public function testProviderList() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
