<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:49.
 */
class ApptBookTest extends PHPUnit_Framework_TestCase {

    /**
     * @var ApptBook
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $pract = Practitioner::getInstance('CCEOW','Dr Joseph Lister','FullName');
        //$this->object = new ApptBook($pract);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ApptBook::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApptBook::handle_exception
     * @todo   Implement testHandle_exception().
     */
    public function testHandle_exception() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApptBook::traverseAppointments
     * @todo   Implement testTraverseAppointments().
     */
    public function testTraverseAppointments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ApptBook::notifyPatients
     * @todo   Implement testNotifyPatients().
     */
    public function testNotifyPatients() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
