<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-13 at 00:50:28.
 */
class BillingTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Billing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Billing;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Billing::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::mylog
     * @todo   Implement testMylog().
     */
    public function testMylog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::recordOrgUsage
     * @todo   Implement testRecordOrgUsage().
     */
    public function testRecordOrgUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::recordAllUsage
     * @todo   Implement testRecordAllUsage().
     */
    public function testRecordAllUsage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::getHowLateDetails
     * @todo   Implement testGetHowLateDetails().
     */
    public function testGetHowLateDetails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::getChargeoverPackage
     * @todo   Implement testGetChargeoverPackage().
     */
    public function testGetChargeoverPackage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::upgradePackageLine
     * @todo   Implement testUpgradePackageLine().
     */
    public function testUpgradePackageLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::createPackage
     * @todo   Implement testCreatePackage().
     */
    public function testCreatePackage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::adjustPackage
     * @todo   Implement testAdjustPackage().
     */
    public function testAdjustPackage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Billing::deleteCustomer
     * @todo   Implement testDeleteCustomer().
     */
    public function testDeleteCustomer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
