<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:44.
 */
class ChargeoverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Chargeover
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Chargeover;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Chargeover::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::createCustomer
     * @todo   Implement testCreateCustomer().
     */
    public function testCreateCustomer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::updateCustomer
     * @todo   Implement testUpdateCustomer().
     */
    public function testUpdateCustomer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::deleteCustomer
     * @todo   Implement testDeleteCustomer().
     */
    public function testDeleteCustomer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::createPackage
     * @todo   Implement testCreatePackage().
     */
    public function testCreatePackage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::createUsage
     * @todo   Implement testCreateUsage().
     */
    public function testCreateUsage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::getCustomer
     * @todo   Implement testGetCustomer().
     */
    public function testGetCustomer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::getCurrentActivePackage
     * @todo   Implement testGetCurrentActivePackage().
     */
    public function testGetCurrentActivePackage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::getPackage
     * @todo   Implement testGetPackage().
     */
    public function testGetPackage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::getPackageLineItems
     * @todo   Implement testGetPackageLineItems().
     */
    public function testGetPackageLineItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::getUsageLineItems
     * @todo   Implement testGetUsageLineItems().
     */
    public function testGetUsageLineItems() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Chargeover::action
     * @todo   Implement testAction().
     */
    public function testAction() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
