<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:45.
 */
class ClickatellTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Clickatell
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Clickatell;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Clickatell::httpSend
     * @todo   Implement testHttpSend().
     */
    public function testHttpSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
