<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:01.
 */
class HowLate_SiteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HowLate_Site
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new HowLate_Site;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HowLate_Site::reduceName
     * @todo   Implement testReduceName().
     */
    public function testReduceName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::checkForDupe
     * @todo   Implement testCheckForDupe().
     */
    public function testCheckForDupe() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createPrivateArea
     * @todo   Implement testCreatePrivateArea().
     */
    public function testCreatePrivateArea() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createCPanelSubdomain
     * @todo   Implement testCreateCPanelSubdomain().
     */
    public function testCreateCPanelSubdomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createOrgRecord
     * @todo   Implement testCreateOrgRecord().
     */
    public function testCreateOrgRecord() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createDefaultClinic
     * @todo   Implement testCreateDefaultClinic().
     */
    public function testCreateDefaultClinic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createDefaultPractitioner
     * @todo   Implement testCreateDefaultPractitioner().
     */
    public function testCreateDefaultPractitioner() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::createDefaultUser
     * @todo   Implement testCreateDefaultUser().
     */
    public function testCreateDefaultUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::sendWelcomeEmail
     * @todo   Implement testSendWelcomeEmail().
     */
    public function testSendWelcomeEmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::installSSL
     * @todo   Implement testInstallSSL().
     */
    public function testInstallSSL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Site::deleteCPanelSubdomain
     * @todo   Implement testDeleteCPanelSubdomain().
     */
    public function testDeleteCPanelSubdomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
