<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-15 at 15:04:34.
 */
class HowLate_TimeTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var HowLate_Time
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        //$this->object = new HowLate_Time;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }



    public function test1MintoHrsMinutes()
    {
        $this->object = HowLate_Time::fromMinutes(1);
        
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'1 minute late');
    }
    public function test0MintoHrsMinutes()
    {
        $this->object = HowLate_Time::fromMinutes(0);
        
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'on time');
    }
    
    public function test105MintoHrsMinutes()
    {
        $this->object = HowLate_Time::fromMinutes(105);
        
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'an hour 45 minutes late');
    }
    
    public function test10Min_toHrsMinutesAdj()
    {
        $p = Practitioner::getInstance('CCEOW','Dr Joseph Lister','FullName');
        
        $this->object = HowLate_Time::fromMinutes(10, $p);
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'on time');
    }
    public function test25Min_toHrsMinutesAdj()
    {
        $p = Practitioner::getInstance('CCEOW','Dr Joseph Lister','FullName');
        
        $this->object = HowLate_Time::fromMinutes(25, $p);
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'15 minutes late');
    }

    
    
    public function test325Min_toHrsMinutesAdj()
    {
        $p = Practitioner::getInstance('CCEOW','Dr Joseph Lister','FullName');
        
        $this->object = HowLate_Time::fromMinutes(325, $p);
        $i = $this->object->toHrsMinutesAdjusted();
        $this->assertEquals($i,'5 hours 15 minutes late');
    }
    
}
