<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:11.
 */
class Howlate_MailerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Howlate_Mailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new Howlate_Mailer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Howlate_Mailer::send
     * @todo   Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Howlate_Mailer::sendHtml
     * @todo   Implement testSendHtml().
     */
    public function testSendHtml() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
