<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:03.
 */
class howlate_dbTest extends PHPUnit_Framework_TestCase {

    /**
     * @var howlate_db
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new howlate_db;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers howlate_db::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getallclinics
     * @todo   Implement testGetallclinics().
     */
    public function testGetallclinics() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getactiveclinics
     * @todo   Implement testGetactiveclinics().
     */
    public function testGetactiveclinics() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getallusers
     * @todo   Implement testGetallusers().
     */
    public function testGetallusers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getPractitioner
     * @todo   Implement testGetPractitioner().
     */
    public function testGetPractitioner() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getPractitionerID
     * @todo   Implement testGetPractitionerID().
     */
    public function testGetPractitionerID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getlatenessesByUDID
     * @todo   Implement testGetlatenessesByUDID().
     */
    public function testGetlatenessesByUDID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getlatenessesByClinic
     * @todo   Implement testGetlatenessesByClinic().
     */
    public function testGetlatenessesByClinic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getOrganisation
     * @todo   Implement testGetOrganisation().
     */
    public function testGetOrganisation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getallpractitioners
     * @todo   Implement testGetallpractitioners().
     */
    public function testGetallpractitioners() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::agent_updatelateness
     * @todo   Implement testAgent_updatelateness().
     */
    public function testAgent_updatelateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::updatelateness
     * @todo   Implement testUpdatelateness().
     */
    public function testUpdatelateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::validatePin
     * @todo   Implement testValidatePin().
     */
    public function testValidatePin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::validateClinic
     * @todo   Implement testValidateClinic().
     */
    public function testValidateClinic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::register
     * @todo   Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::unregister
     * @todo   Implement testUnregister().
     */
    public function testUnregister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::place
     * @todo   Implement testPlace().
     */
    public function testPlace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::place2
     * @todo   Implement testPlace2().
     */
    public function testPlace2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::displace
     * @todo   Implement testDisplace().
     */
    public function testDisplace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::write_error
     * @todo   Implement testWrite_error().
     */
    public function testWrite_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::trlog
     * @todo   Implement testTrlog().
     */
    public function testTrlog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::get_user_data
     * @todo   Implement testGet_user_data().
     */
    public function testGet_user_data() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::isValidPassword
     * @todo   Implement testIsValidPassword().
     */
    public function testIsValidPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::gettimezones
     * @todo   Implement testGettimezones().
     */
    public function testGettimezones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::save_reset_token
     * @todo   Implement testSave_reset_token().
     */
    public function testSave_reset_token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::check_token
     * @todo   Implement testCheck_token().
     */
    public function testCheck_token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::change_password
     * @todo   Implement testChange_password().
     */
    public function testChange_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::update_org
     * @todo   Implement testUpdate_org().
     */
    public function testUpdate_org() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::create_org
     * @todo   Implement testCreate_org().
     */
    public function testCreate_org() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::create_user
     * @todo   Implement testCreate_user().
     */
    public function testCreate_user() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::create_default_clinic
     * @todo   Implement testCreate_default_clinic().
     */
    public function testCreate_default_clinic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::create_default_practitioner
     * @todo   Implement testCreate_default_practitioner().
     */
    public function testCreate_default_practitioner() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getNextOrgID
     * @todo   Implement testGetNextOrgID().
     */
    public function testGetNextOrgID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getNextPractID
     * @todo   Implement testGetNextPractID().
     */
    public function testGetNextPractID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getAllLatenesses
     * @todo   Implement testGetAllLatenesses().
     */
    public function testGetAllLatenesses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::deleteLate
     * @todo   Implement testDeleteLate().
     */
    public function testDeleteLate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::deleteLateByKey
     * @todo   Implement testDeleteLateByKey().
     */
    public function testDeleteLateByKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getallcountries
     * @todo   Implement testGetallcountries().
     */
    public function testGetallcountries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getallorgs
     * @todo   Implement testGetallorgs().
     */
    public function testGetallorgs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getLateTimezones
     * @todo   Implement testGetLateTimezones().
     */
    public function testGetLateTimezones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getLatesAndSessions
     * @todo   Implement testGetLatesAndSessions().
     */
    public function testGetLatesAndSessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::updatesessions
     * @todo   Implement testUpdatesessions().
     */
    public function testUpdatesessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::enqueueNotificationNew
     * @todo   Implement testEnqueueNotificationNew().
     */
    public function testEnqueueNotificationNew() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::enqueueNotification
     * @todo   Implement testEnqueueNotification().
     */
    public function testEnqueueNotification() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getSingleLateness
     * @todo   Implement testGetSingleLateness().
     */
    public function testGetSingleLateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::deleteOldLates
     * @todo   Implement testDeleteOldLates().
     */
    public function testDeleteOldLates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getClinicIntegration
     * @todo   Implement testGetClinicIntegration().
     */
    public function testGetClinicIntegration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::createClinicIntegration
     * @todo   Implement testCreateClinicIntegration().
     */
    public function testCreateClinicIntegration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::updateClinicIntegration
     * @todo   Implement testUpdateClinicIntegration().
     */
    public function testUpdateClinicIntegration() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getQueuedNotifications
     * @todo   Implement testGetQueuedNotifications().
     */
    public function testGetQueuedNotifications() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::dequeueNotification
     * @todo   Implement testDequeueNotification().
     */
    public function testDequeueNotification() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::smslog
     * @todo   Implement testSmslog().
     */
    public function testSmslog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::deleteSubdomain
     * @todo   Implement testDeleteSubdomain().
     */
    public function testDeleteSubdomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers howlate_db::getBySubdomain
     * @todo   Implement testGetBySubdomain().
     */
    public function testGetBySubdomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
