<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-14 at 12:05:45.
 */
class HowLate_SMSTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HowLate_SMS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HowLate_SMS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HowLate_SMS::httpSend
     * @todo   Implement testHttpSend().
     */
    public function testHttpSend() {
        // Remove the following lines when you implement this test.
        
        $orgid = 'CCEOW';
        $udid = '61403569377';
        $message = 'This is from ' .  __METHOD__;
        $this->object->httpSend($orgid, $udid, $message);
        
    }
    /**
     * @covers HowLate_SMS::httpSend
     * @todo   Implement testHttpSend().
     */
    public function testHttpSendMock() {
        // Remove the following lines when you implement this test.
        
        $orgid = 'CCEOW';
        $udid = '61403569377';
        $message = 'This is from ' .  __METHOD__;
        
        $mock = new HowLate_SMS(new MockClickatell());
        
        $mock->httpSend($orgid, $udid, $message);
        
    }

}
