<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:15.
 */
class HowLate_UtilTest extends PHPUnit_Framework_TestCase {

    /**
     * @var HowLate_Util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HowLate_Util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers HowLate_Util::admin_sms
     * @todo   Implement testAdmin_sms().
     */
    public function testAdmin_sms() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::admin_email
     * @todo   Implement testAdmin_email().
     */
    public function testAdmin_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::cpanelUser
     * @todo   Implement testCpanelUser().
     */
    public function testCpanelUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::cpanelPassword
     * @todo   Implement testCpanelPassword().
     */
    public function testCpanelPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::mysqlDb
     * @todo   Implement testMysqlDb().
     */
    public function testMysqlDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::mysqlBillingDb
     * @todo   Implement testMysqlBillingDb().
     */
    public function testMysqlBillingDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::mysqlAnalyticsDb
     * @todo   Implement testMysqlAnalyticsDb().
     */
    public function testMysqlAnalyticsDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::mysqlUser
     * @todo   Implement testMysqlUser().
     */
    public function testMysqlUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::mysqlPassword
     * @todo   Implement testMysqlPassword().
     */
    public function testMysqlPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::basePath
     * @todo   Implement testBasePath().
     */
    public function testBasePath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::masterPath
     * @todo   Implement testMasterPath().
     */
    public function testMasterPath() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::noreplySmtpUsername
     * @todo   Implement testNoreplySmtpUsername().
     */
    public function testNoreplySmtpUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::noreplySmtpPassword
     * @todo   Implement testNoreplySmtpPassword().
     */
    public function testNoreplySmtpPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::chargeoverUsername
     * @todo   Implement testChargeoverUsername().
     */
    public function testChargeoverUsername() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::chargeoverPassword
     * @todo   Implement testChargeoverPassword().
     */
    public function testChargeoverPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::chargeoverApiUrl
     * @todo   Implement testChargeoverApiUrl().
     */
    public function testChargeoverApiUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::tobase10
     * @todo   Implement testTobase10().
     */
    public function testTobase10() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::tobase26
     * @todo   Implement testTobase26().
     */
    public function testTobase26() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::checkdigit
     * @todo   Implement testCheckdigit().
     */
    public function testCheckdigit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::validatePin
     * @todo   Implement testValidatePin().
     */
    public function testValidatePin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::toHHMMSS
     * @todo   Implement testToHHMMSS().
     */
    public function testToHHMMSS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::orgFromPin
     * @todo   Implement testOrgFromPin().
     */
    public function testOrgFromPin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::idFromPin
     * @todo   Implement testIdFromPin().
     */
    public function testIdFromPin() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::startsWith
     * @todo   Implement testStartsWith().
     */
    public function testStartsWith() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::endsWith
     * @todo   Implement testEndsWith().
     */
    public function testEndsWith() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::logoURL
     * @todo   Implement testLogoURL().
     */
    public function testLogoURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::logoWhiteBG
     * @todo   Implement testLogoWhiteBG().
     */
    public function testLogoWhiteBG() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::diag
     * @todo   Implement testDiag().
     */
    public function testDiag() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::secondsSinceMidnight
     * @todo   Implement testSecondsSinceMidnight().
     */
    public function testSecondsSinceMidnight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::dayName
     * @todo   Implement testDayName().
     */
    public function testDayName() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::register
     * @todo   Implement testRegister().
     */
    public function testRegister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::getSSLCertificate
     * @todo   Implement testGetSSLCertificate().
     */
    public function testGetSSLCertificate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::googleMapsURL
     * @todo   Implement testGoogleMapsURL().
     */
    public function testGoogleMapsURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::getLateTimezones
     * @todo   Implement testGetLateTimezones().
     */
    public function testGetLateTimezones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::getLatesAndSessions
     * @todo   Implement testGetLatesAndSessions().
     */
    public function testGetLatesAndSessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::deleteOldLates
     * @todo   Implement testDeleteOldLates().
     */
    public function testDeleteOldLates() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::getQueuedNotifications
     * @todo   Implement testGetQueuedNotifications().
     */
    public function testGetQueuedNotifications() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::dequeueNotification
     * @todo   Implement testDequeueNotification().
     */
    public function testDequeueNotification() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::deleteSubdomain
     * @todo   Implement testDeleteSubdomain().
     */
    public function testDeleteSubdomain() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::to_xudid
     * @todo   Implement testTo_xudid().
     */
    public function testTo_xudid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers HowLate_Util::to_udid
     * @todo   Implement testTo_udid().
     */
    public function testTo_udid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
