<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:06.
 */
class LoggingTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Logging
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Logging;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Logging::smslog
     * @todo   Implement testSmslog().
     */
    public function testSmslog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logging::trlog
     * @todo   Implement testTrlog().
     */
    public function testTrlog() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logging::write_error
     * @todo   Implement testWrite_error().
     */
    public function testWrite_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logging::stdout
     * @todo   Implement testStdout().
     */
    public function testStdout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Logging::deleteOld
     * @todo   Implement testDeleteOld().
     */
    public function testDeleteOld() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
