<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:47.
 */
class NotifierTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Notifier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //$this->object = new Notifier($OrgID, $ClinicID, $entire_appt_book, $TimeNow);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Notifier::processNotifications
     * @todo   Implement testProcessNotifications().
     */
    public function testProcessNotifications() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
