<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:46.
 */
class OrganisationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Organisation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Organisation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Organisation::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::getRelated
     * @todo   Implement testGetRelated().
     */
    public function testGetRelated() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::findUsers
     * @todo   Implement testFindUsers().
     */
    public function testFindUsers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::isValidPassword
     * @todo   Implement testIsValidPassword().
     */
    public function testIsValidPassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::getLatenesses
     * @todo   Implement testGetLatenesses().
     */
    public function testGetLatenesses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::getTimezones
     * @todo   Implement testGetTimezones().
     */
    public function testGetTimezones() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::getCountries
     * @todo   Implement testGetCountries().
     */
    public function testGetCountries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::update_org
     * @todo   Implement testUpdate_org().
     */
    public function testUpdate_org() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::update_billing
     * @todo   Implement testUpdate_billing().
     */
    public function testUpdate_billing() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::createOrg
     * @todo   Implement testCreateOrg().
     */
    public function testCreateOrg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::getNextOrgID
     * @todo   Implement testGetNextOrgID().
     */
    public function testGetNextOrgID() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::unregister
     * @todo   Implement testUnregister().
     */
    public function testUnregister() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::sendResetEmails
     * @todo   Implement testSendResetEmails().
     */
    public function testSendResetEmails() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::checkToken
     * @todo   Implement testCheckToken().
     */
    public function testCheckToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::check_token
     * @todo   Implement testCheck_token().
     */
    public function testCheck_token() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::deleteLateByKey
     * @todo   Implement testDeleteLateByKey().
     */
    public function testDeleteLateByKey() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Organisation::saveResetToken
     * @todo   Implement testSaveResetToken().
     */
    public function testSaveResetToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
