<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:14:58.
 */
class OrgUserTest extends PHPUnit_Framework_TestCase {

    /**
     * @var OrgUser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new OrgUser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers OrgUser::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OrgUser::changePassword
     * @todo   Implement testChangePassword().
     */
    public function testChangePassword() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OrgUser::change_password
     * @todo   Implement testChange_password().
     */
    public function testChange_password() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers OrgUser::createUser
     * @todo   Implement testCreateUser().
     */
    public function testCreateUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
