<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-31 at 00:15:12.
 */
class PractitionerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Practitioner
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Practitioner;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Practitioner::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
        
        $p = Practitioner::getInstance($OrgID = 'CCEOW', $FieldValue, 'FullName');
       
    }

    /**
     * @covers Practitioner::getInstance2
     * @todo   Implement testGetInstance2().
     */
    public function testGetInstance2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::logoURL
     * @todo   Implement testLogoURL().
     */
    public function testLogoURL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::updateLateness
     * @todo   Implement testUpdateLateness().
     */
    public function testUpdateLateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::updatesessions
     * @todo   Implement testUpdatesessions().
     */
    public function testUpdatesessions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::isSessionEnded
     * @todo   Implement testIsSessionEnded().
     */
    public function testIsSessionEnded() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::place2
     * @todo   Implement testPlace2().
     */
    public function testPlace2() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::place
     * @todo   Implement testPlace().
     */
    public function testPlace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::displace
     * @todo   Implement testDisplace().
     */
    public function testDisplace() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::createDefaultPractitioner
     * @todo   Implement testCreateDefaultPractitioner().
     */
    public function testCreateDefaultPractitioner() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::enqueueAdjustedMessage
     * @todo   Implement testEnqueueAdjustedMessage().
     */
    public function testEnqueueAdjustedMessage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::enqueueNotification
     * @todo   Implement testEnqueueNotification().
     */
    public function testEnqueueNotification() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::getCurrentLateness
     * @todo   Implement testGetCurrentLateness().
     */
    public function testGetCurrentLateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::getActualLateness
     * @todo   Implement testGetActualLateness().
     */
    public function testGetActualLateness() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::getLatenessMsg
     * @todo   Implement testGetLatenessMsg().
     */
    public function testGetLatenessMsg() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::setAppointmentBook
     * @todo   Implement testSetAppointmentBook().
     */
    public function testSetAppointmentBook() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::predictConsultTimes
     * @todo   Implement testPredictConsultTimes().
     */
    public function testPredictConsultTimes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Practitioner::LatenessUpdate
     * @todo   Implement testLatenessUpdate().
     */
    public function testLatenessUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
